// Probably not feasible for a large inventory to store all items in a single file.
export const inventory = {
    backpack: {
        name: 'Sauce Labs Backpack',
        description: 'A red backpack with the Swag Labs logo.',
        price: 29.99,
        image: 'https://www.saucedemo.com/static/media/sauce-backpack-1200x1500.jpg',
        id: 'sauce-labs-backpack',
        itemNum: 4,
    },
    bikeLight: {
        name: 'Sauce Labs Bike Light',
        description: 'A bike light with the Swag Labs logo.',
        price: 9.99,
        image: 'https://www.saucedemo.com/static/media/sauce-bike-light-1200x1500.jpg',
        id: 'sauce-labs-bike-light',
        itemNum: 0,
    },
    boltShirt: {
        name: 'Sauce Labs Bolt T-Shirt',
        description: 'A t-shirt with the Swag Labs logo.',
        price: 15.99,
        image: 'https://www.saucedemo.com/static/media/sauce-bolt-t-shirt-1200x1500.jpg',
        id: 'sauce-labs-bolt-t-shirt',
        itemNum: 1,
    },
    fleeceJacket: {
        name: 'Sauce Labs Fleece Jacket',
        description: 'A fleece jacket with the Swag Labs logo.',
        price: 49.99,
        image: 'https://www.saucedemo.com/static/media/sauce-fleece-jacket-1200x1500.jpg',
        id: 'sauce-labs-fleece-jacket',
        itemNum: 5,
    },
    onesie: {
        name: 'Sauce Labs Onesie',
        description: 'A onesie with the Swag Labs logo.',
        price: 7.99,
        image: 'https://www.saucedemo.com/static/media/sauce-onesie-1200x1500.jpg',
        id: 'sauce-labs-onesie',
        itemNum: 2,
    },
    redShirt: {
        name: 'Test.allTheThings() T-Shirt (Red)',
        description: 'A red t-shirt with the Swag Labs logo.',
        price: 15.99,
        image: 'https://www.saucedemo.com/static/media/red-tshirt-1200x1500.jpg',
        id: 'test.allthethings()-t-shirt-(red)',
        itemNum: 3,
    },
};
